---
apiVersion: v1
kind: Service
metadata:
  name: sshanmugam-clamav-svc
  namespace: { { .Values.namespace } }
  labels:
    app: sshanmugam-clamav
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32000
      protocol: TCP
      name: clamav-port
  selector:
    app: sshanmugam-clamav
